### ISSUE TITLE
Did I push sleep to it limit?

### ISSUE THREAD

**Issue by HiveHypnotic** [leftCoast/LC_baseTools#5]
Hello Jim,
I didn't know how to contact you so I am going to ask you a question here as
I am not sure what the issue really is, or even if there is an issue.

Here is a wokwi example; Keep in mind it might be an issue with wokwi as I have not 
tried this example on actual arduino.

endlessBlinkTimer.ino ; that I did based on your examples.
https://wokwi.com/arduino/projects/322488072025408082

I was able to blink 12 LED for five minutes every hour; however, 
the Serial.println at the very bottom of the loop never prints.

Of course when I reduce the default vars to much smaller numbers it works
as expected; and it does print to the serial every minute.

I am a fan of your work, and appreciate your time spent with your code and your
examples. I am just working with your code to learn from someone that knows how to code
so I learn the right way the first time.

I am also learning git and I guess I should learn that as well.

Anyway, I found this to be interesting and thought you might be interested
in this example of yours that I messed up. As a way of learning.

Take care, and thanks for your help, not_a_borg

P.S. I am just doing this as an exercise to train my memory, as I have a disability.
There is no need to fix this, or work on the code. I just wanted to let you know
that I was able to mess it up. LOL 

I be back in 8 hours.

P.S. I know this is a stupid way to code a clock; as a clock only needs 
three blinkers Hour, Minute, and Second.

**Comment by leftCoast** [comment]
How many hours did you run this for?Because it'll take at least an hour
before the first printout.

-jim

**Comment by HiveHypnotic** [comment]
Hi Jim;
I feel so dumb, HOW did I not see what I did in the setup();

Thanks, for letting me try github issue.

I hope you laughed when you saw the setup() function.

Many thanks for taking the time to look at my mess, and your feedback ;-)

**Comment by leftCoast** [comment]
No worries. Have fun!
